package com.midas.d3.persistence.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.Instant;
import java.util.UUID;

/**
 * JPA entity mapping to the {@code midas_evolution_log} table.
 *
 * <p>One record is stored for every completed Evolution Agent analysis cycle.
 * The {@code run_id} foreign key links the report to the original pipeline run;
 * ON DELETE CASCADE ensures the log is removed when the parent run is deleted.
 *
 * <p>Schema is managed by Flyway migration {@code V2__evolution_log.sql}.
 */
@Entity
@Table(name = "midas_evolution_log")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class MidasEvolutionLogEntity {

    /** UUID primary key — generated by the application before persistence. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    /** FK to {@code midas_run.id} — the pipeline run this report belongs to. */
    @Column(name = "run_id", nullable = false, length = 255)
    private String runId;

    /** Full Markdown refactoring report produced by the EvolutionAgent. */
    @Column(name = "refactoring_report", columnDefinition = "TEXT")
    private String refactoringReport;

    /** UTC timestamp when this record was created. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @PrePersist
    protected void prePersist() {
        if (this.createdAt == null) {
            this.createdAt = Instant.now();
        }
    }
}
