package com.midas.d3.persistence.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.Instant;
import java.util.UUID;

/**
 * JPA entity mapping to the {@code midas_agent_log} table.
 *
 * <p>Records a single agent invocation within a pipeline run, capturing the
 * agent's output, execution timing, and token usage for analytics and auditing.
 *
 * <p>The UUID primary key is generated by Hibernate 6's built-in UUID strategy
 * (application-side generation via {@link java.util.UUID#randomUUID()}).
 */
@Entity
@Table(name = "midas_agent_log")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class MidasAgentLogEntity {

    /** Surrogate UUID primary key — generated by Hibernate at persist time. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    /** Parent pipeline run. Loaded lazily to avoid unnecessary joins. */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "run_id", nullable = false, updatable = false)
    private MidasRunEntity run;

    /**
     * Agent class name / role identifier (e.g. {@code "SystemAnalystAgent"}).
     * Used for analytics queries filtering by agent type.
     */
    @Column(name = "agent_type", length = 100)
    private String agentType;

    /** Full raw LLM output or error message from this invocation. */
    @Column(name = "raw_output", columnDefinition = "TEXT")
    private String rawOutput;

    /** Number of prompt tokens consumed (0 when not tracked by the LLM client). */
    @Column(name = "prompt_tokens", nullable = false)
    @Builder.Default
    private int promptTokens = 0;

    /** Number of completion tokens consumed (0 when not tracked). */
    @Column(name = "completion_tokens", nullable = false)
    @Builder.Default
    private int completionTokens = 0;

    @Column(name = "model_id", length = 100)
    private String modelId;

    /** Wall-clock execution time of {@code agent.execute()} in milliseconds. */
    @Column(name = "execution_time_ms", nullable = false)
    @Builder.Default
    private long executionTimeMs = 0L;

    /** {@code true} if the agent threw an exception during this invocation. */
    @Column(name = "is_error", nullable = false)
    @Builder.Default
    private boolean isError = false;

    /** UTC timestamp when this log entry was created. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    // ── JPA lifecycle callback ────────────────────────────────────────────────

    @PrePersist
    protected void prePersist() {
        this.createdAt = Instant.now();
    }
}
