package com.midas.d3.persistence.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.Instant;

/**
 * JPA entity mapping to the {@code midas_run} table.
 *
 * <p>Represents one full pipeline execution. Fields are updated throughout the
 * pipeline lifecycle by {@link com.midas.d3.persistence.PersistenceService}.
 *
 * <p>Schema is managed exclusively by Flyway ({@code V1__init_schema.sql}).
 * Hibernate is configured with {@code ddl-auto=validate} — it only verifies
 * mappings against the existing schema and never alters it.
 */
@Entity
@Table(name = "midas_run")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class MidasRunEntity {

    /** Pipeline run ID (UUID string generated by the application). */
    @Id
    @Column(name = "id", length = 255, nullable = false, updatable = false)
    private String id;

    /** Telegram chat ID that initiated this run; {@code null} for REST-initiated runs. */
    @Column(name = "chat_id")
    private Long chatId;

    /** Raw user idea, potentially enriched with Human-in-the-Loop clarifications. */
    @Column(name = "raw_user_idea", columnDefinition = "TEXT")
    private String rawUserIdea;

    /**
     * Current pipeline status.
     * Lifecycle values: {@code STARTED → SYSTEM_ANALYSIS → … → COMPLETED / ERROR}.
     */
    @Column(name = "status", length = 50)
    private String status;

    /** Absolute path to the generated artifacts ZIP file; set on COMPLETED. */
    @Column(name = "artifact_path", length = 1000)
    private String artifactPath;

    /** Aggregated prompt token count across all agent invocations. */
    @Column(name = "total_prompt_tokens", nullable = false)
    @Builder.Default
    private int totalPromptTokens = 0;

    /** Aggregated completion token count across all agent invocations. */
    @Column(name = "total_completion_tokens", nullable = false)
    @Builder.Default
    private int totalCompletionTokens = 0;

    /** Flag indicating whether a human reviewer marked the output for refactoring. */
    @Column(name = "needs_refactoring", nullable = false)
    @Builder.Default
    private boolean needsRefactoring = false;

    /** UTC timestamp when this run record was first inserted. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** UTC timestamp of the last update to this record. */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    // ── JPA lifecycle callbacks ───────────────────────────────────────────────

    @PrePersist
    protected void prePersist() {
        Instant now = Instant.now();
        this.createdAt = now;
        this.updatedAt = now;
    }

    @PreUpdate
    protected void preUpdate() {
        this.updatedAt = Instant.now();
    }
}
