package com.midas.d3.statemachine;

import com.midas.d3.statemachine.action.*;
import com.midas.d3.statemachine.guard.BuildRemediationAvailableGuard;
import com.midas.d3.statemachine.guard.BuildRemediationExhaustedGuard;
import com.midas.d3.statemachine.guard.QualityBackstopGuard;
import com.midas.d3.statemachine.guard.RemediationAvailableGuard;
import com.midas.d3.statemachine.guard.RemediationExhaustedGuard;
import com.midas.d3.statemachine.guard.RetriesExhaustedGuard;
import com.midas.d3.statemachine.guard.SkipIntegrationStageGuard;
import com.midas.d3.statemachine.guard.ValidationSucceededGuard;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.context.annotation.Configuration;
import org.springframework.statemachine.config.EnableStateMachineFactory;
import org.springframework.statemachine.config.StateMachineConfigurerAdapter;
import org.springframework.statemachine.config.builders.StateMachineConfigurationConfigurer;
import org.springframework.statemachine.config.builders.StateMachineStateConfigurer;
import org.springframework.statemachine.config.builders.StateMachineTransitionConfigurer;
import org.springframework.statemachine.config.configurers.StateConfigurer;
import org.springframework.statemachine.listener.StateMachineListenerAdapter;
import org.springframework.statemachine.state.State;

import java.util.EnumSet;

/**
 * Spring State Machine configuration for the MIDAS_D3 pipeline.
 *
 * <h2>Retry protocol — CHOICE pseudo-state pattern</h2>
 * Each processing stage uses a dedicated CHOICE pseudo-state for reliable
 * conditional routing after {@code SUBMIT_RESULT}:
 * <pre>
 *   STAGE ──SUBMIT_RESULT──► STAGE_CHOICE   [action: ValidateAndCaptureAction]
 *                                │
 *          ┌────────────────────┤ first  [guard: ValidationSucceededGuard]
 *          │ NEXT_STAGE ◄───────┤        [action: StoreArtifactAction]
 *          │                    │
 *          │         ───────────┤ then   [guard: RetriesExhaustedGuard]
 *          │ ERROR ◄────────────┤        [action: PipelineErrorAction]
 *          │                    │
 *          │         ───────────┘ last   (else — retries < max)
 *          │ STAGE ◄────────────         [action: IncrementRetryAction]
 * </pre>
 *
 * <h2>Agent auto-drive (Stage 6 addition)</h2>
 * When a pipeline is started in {@link PipelineContextKeys#AUTO_MODE_KEY auto-mode}
 * (e.g. via the Telegram bot), an {@link AgentEntryAction} is registered as a state-entry
 * action for every processing state. On entry it asynchronously dispatches the corresponding
 * {@link com.midas.d3.agent.base.BaseMidasAgent} and, upon completion, fires either
 * {@link MidasEvent#SUBMIT_RESULT} (success) or {@link MidasEvent#CRITICAL_FAILURE}
 * (agent exhausted all internal retries).
 *
 * <h2>CRITICAL_FAILURE fast-path</h2>
 * Each processing state has an additional {@code CRITICAL_FAILURE → ERROR} external
 * transition handled by {@link CriticalFailureAction}. This bypasses the CHOICE-state
 * retry loop and terminates the pipeline immediately.
 *
 * <h2>Topology source of truth</h2>
 * The processing-stage ordering, the stage→CHOICE pairing, and the stage→next-stage
 * successor relationship are NOT hardcoded here. They are owned by {@link PipelineTopology}
 * and the per-stage state declarations and transitions below are generated by iterating it.
 * This guarantees the state machine and {@link com.midas.d3.statemachine.action.StoreArtifactAction}
 * can never disagree about routing, and makes pipeline-shape changes a single declarative edit.
 */
@Slf4j
@Configuration
@EnableStateMachineFactory
@RequiredArgsConstructor
public class PipelineStateMachineConfig
        extends StateMachineConfigurerAdapter<MidasState, MidasEvent> {

    private final ValidationSucceededGuard   validationSucceededGuard;
    private final SkipIntegrationStageGuard  skipIntegrationStageGuard;
    private final RetriesExhaustedGuard      retriesExhaustedGuard;
    private final RemediationAvailableGuard  remediationAvailableGuard;
    private final RemediationExhaustedGuard  remediationExhaustedGuard;
    private final BuildRemediationAvailableGuard buildRemediationAvailableGuard;
    private final BuildRemediationExhaustedGuard buildRemediationExhaustedGuard;
    private final InitContextAction          initContextAction;
    private final ValidateAndCaptureAction   validateAndCaptureAction;
    private final StoreArtifactAction        storeArtifactAction;
    private final IncrementRetryAction       incrementRetryAction;
    private final PipelineErrorAction        pipelineErrorAction;
    private final ProductReviewRejectionAction productReviewRejectionAction;
    private final QualityBackstopGuard       qualityBackstopGuard;
    private final QualityBackstopAction      qualityBackstopAction;
    private final RemediationInitAction      remediationInitAction;
    private final BuildRemediationInitAction buildRemediationInitAction;
    private final BuildFailureErrorAction    buildFailureErrorAction;
    private final AgentEntryAction           agentEntryAction;
    private final CriticalFailureAction      criticalFailureAction;
    private final PipelineCompletionAction   completionAction;
    private final DegradeToGapsAction        degradeToGapsAction;
    private final PauseForInputAction        pauseForInputAction;
    private final PipelineTopology           topology;

    // ── States ───────────────────────────────────────────────────────────────

    @Override
    public void configure(StateMachineStateConfigurer<MidasState, MidasEvent> states)
            throws Exception {
        // COMPLETED and ERROR are NOT declared as SSM terminal end-states because
        // both must accept the RESET event to allow pipeline reuse.
        StateConfigurer<MidasState, MidasEvent> cfg = states.withStates()
                .initial(MidasState.IDLE);

        // CHOICE pseudo-states — declared from the topology so they stay in lock-step
        // with the processing stages they route for.
        for (MidasState choice : topology.choiceStates()) {
            cfg = cfg.choice(choice);
        }

        cfg = cfg.states(EnumSet.allOf(MidasState.class));

        // Agent entry actions (only fire in AUTO_MODE) — one per processing stage.
        for (MidasState stage : topology.processingStages()) {
            cfg = cfg.stateEntry(stage, agentEntryAction);
        }

        cfg
                // ── Human-in-the-Loop pause state ─────────────────────────────
                .stateEntry(MidasState.WAITING_FOR_USER_INPUT, pauseForInputAction)
                // ── Completion: package + deliver artifacts to Telegram ────────
                .stateEntry(MidasState.COMPLETED,            completionAction)
                // ── Graceful degradation: same packaging/delivery path, degraded status ──
                // Reuses the completion action; DEGRADED_COMPLETION (set by DegradeToGapsAction on the
                // inbound transition) makes it finalize as COMPLETED_WITH_GAPS rather than COMPLETED.
                .stateEntry(MidasState.COMPLETED_WITH_GAPS,  completionAction);
    }

    // ── Transitions ───────────────────────────────────────────────────────────

    @Override
    public void configure(StateMachineTransitionConfigurer<MidasState, MidasEvent> transitions)
            throws Exception {

        StateMachineTransitionConfigurer<MidasState, MidasEvent> t = transitions;

        // ── Entry: IDLE → first processing stage ─────────────────────────────
        t = t.withExternal()
                .source(MidasState.IDLE).target(topology.firstStage())
                .event(MidasEvent.START)
                .action(initContextAction)
                .and();

        // ── Per-stage processing blocks, generated from PipelineTopology ─────
        // For each stage: SUBMIT_RESULT → CHOICE (validate), then the CHOICE routes to
        // next-stage (success) / ERROR (retries exhausted) / same-stage (retry), plus a
        // CRITICAL_FAILURE fast-path straight to ERROR.
        for (MidasState stage : topology.processingStages()) {
            MidasState choice = topology.choiceFor(stage);
            MidasState next   = topology.nextStage(stage);

            t = t.withExternal()
                    .source(stage).target(choice)
                    .event(MidasEvent.SUBMIT_RESULT)
                    .action(validateAndCaptureAction)
                    .and();

            if (topology.isQualityGate(stage)) {
                t = t.withChoice()
                        .source(choice)
                        .first(MidasState.CODE_GENERATION, remediationAvailableGuard, remediationInitAction)
                        // Quality backstop: a REJECT that exhausted remediation but carries substantive
                        // deterministic proof (gated rubric fully satisfied + build OK) completes as
                        // PASS_WITH_NOTES instead of ERROR — checked BEFORE the exhausted→ERROR route.
                        .then(next, qualityBackstopGuard, qualityBackstopAction)
                        .then(MidasState.ERROR, remediationExhaustedGuard, productReviewRejectionAction)
                        .then(next, validationSucceededGuard, storeArtifactAction)
                        .then(MidasState.ERROR, retriesExhaustedGuard, pipelineErrorAction)
                        .last(stage, incrementRetryAction)
                        .and();
            } else if (stage == MidasState.BUILD_VERIFICATION) {
                // Self-healing build gate. A structurally-valid report is always captured by
                // ValidateAndCaptureAction; the build OUTCOME then routes:
                //   FAILED + budget    → CODE_GENERATION (inject diagnostics, regenerate)
                //   FAILED + exhausted → ERROR
                //   SUCCESS            → next stage (SecOps audit)
                //   malformed report   → standard retry / ERROR
                t = t.withChoice()
                        .source(choice)
                        .first(MidasState.CODE_GENERATION, buildRemediationAvailableGuard, buildRemediationInitAction)
                        .then(MidasState.ERROR, buildRemediationExhaustedGuard, buildFailureErrorAction)
                        .then(next, validationSucceededGuard, storeArtifactAction)
                        .then(MidasState.ERROR, retriesExhaustedGuard, pipelineErrorAction)
                        .last(stage, incrementRetryAction)
                        .and();
            } else if (stage == MidasState.ARCHITECTURE_DESIGN) {
                t = t.withChoice()
                        .source(choice)
                        .first(MidasState.CODE_GENERATION, skipIntegrationStageGuard, storeArtifactAction)
                        .then(MidasState.INTEGRATION_STRATEGY, validationSucceededGuard, storeArtifactAction)
                        .then(MidasState.ERROR, retriesExhaustedGuard, pipelineErrorAction)
                        .last(stage, incrementRetryAction)
                        .and();
            } else {
                t = t.withChoice()
                        .source(choice)
                        .first(next, validationSucceededGuard, storeArtifactAction)
                        .then(MidasState.ERROR, retriesExhaustedGuard, pipelineErrorAction)
                        .last(stage, incrementRetryAction)
                        .and();
            }

            t = t.withExternal()
                    .source(stage).target(MidasState.ERROR)
                    .event(MidasEvent.CRITICAL_FAILURE)
                    .action(criticalFailureAction)
                    .and();
        }

        t
        // ── Human-in-the-Loop: pause when Analyst needs clarification ────────
            .withExternal()
                .source(topology.firstStage()).target(MidasState.WAITING_FOR_USER_INPUT)
                .event(MidasEvent.ANALYST_NEEDS_INFO)
                .and()

        // ── Human-in-the-Loop: resume with user's reply ───────────────────────
            .withExternal()
                .source(MidasState.WAITING_FOR_USER_INPUT).target(topology.firstStage())
                .event(MidasEvent.USER_REPLIED)
                .and()

        // ── Human-in-the-Loop: allow abort from waiting state ─────────────────
            .withExternal()
                .source(MidasState.WAITING_FOR_USER_INPUT).target(MidasState.IDLE)
                .event(MidasEvent.RESET)
                .and()

        // ── Graceful degradation: unhealable CODE_GENERATION gap → partial delivery ──
        // Fired by AgentDispatcher (DEGRADE_ARTIFACT) only when a best-effort partial artifact is
        // salvageable and degradation is enabled. DegradeToGapsAction stores the partial + an honest
        // coverage report and flags DEGRADED_COMPLETION; the COMPLETED_WITH_GAPS stateEntry then
        // packages/delivers via the same completion path — the client gets an artifact, never a crash.
            .withExternal()
                .source(MidasState.CODE_GENERATION).target(MidasState.COMPLETED_WITH_GAPS)
                .event(MidasEvent.DEGRADE_ARTIFACT)
                .action(degradeToGapsAction)
                .and()

        // ── Terminal resets ───────────────────────────────────────────────────
            .withExternal()
                .source(MidasState.ERROR).target(MidasState.IDLE)
                .event(MidasEvent.RESET)
                .and()
            .withExternal()
                .source(MidasState.COMPLETED).target(MidasState.IDLE)
                .event(MidasEvent.RESET)
                .and()
            .withExternal()
                .source(MidasState.COMPLETED_WITH_GAPS).target(MidasState.IDLE)
                .event(MidasEvent.RESET);
    }

    // ── Global listener (structured logging) ─────────────────────────────────

    @Override
    public void configure(StateMachineConfigurationConfigurer<MidasState, MidasEvent> config)
            throws Exception {
        config.withConfiguration()
                .autoStartup(false)
                .listener(new StateMachineListenerAdapter<>() {
                    @Override
                    public void stateChanged(State<MidasState, MidasEvent> from,
                                             State<MidasState, MidasEvent> to) {
                        String fromId = from != null ? from.getId().name() : "NONE";
                        String toId   = to   != null ? to.getId().name()   : "NONE";
                        if (!toId.endsWith("_CHOICE")) {
                            log.info("[StateMachine] {} → {}", fromId, toId);
                        }
                    }
                });
    }
}
